export const characterMock = {
  id: "",
  attack: 20,
  defense: 30,
  maxHealth: 100,
  currentHealth: 100,
  avatarUrl: "",
  createdAt: "",
  name: "Rocky Balboa",
  ability1: {
    id: "",
    name: "heal me",
    metadata: "{}",
    created_at: "",
    description: "",
  },
  ability2: {
    id: "",
    name: "run away",
    metadata: "{}",
    created_at: "",
    description: "",
  },
  ability3: {
    id: "",
    name: "basic punch",
    metadata: "{}",
    created_at: "",
    description: "",
  },
};
